import React from 'react';
import '../styles/workspace.css';

export default function DiagnosticReport({ report, onReturnToDashboard }) {
  const {
    patientId,
    patientName,
    scanDate,
    label,
    confidence,
    isNormal,
  } = report;

  const formattedDate = new Date(scanDate).toLocaleString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
    hour: '2-digit', minute: '2-digit'
  });

  const handleDownloadPDF = () => {
    // Simulate PDF download trigger
    const content = `
TRAVELPAL DIAGNOSTIC REPORT
==============================
Patient ID: ${patientId}
Patient Name: ${patientName}
Scan Date: ${formattedDate}

ANALYSIS RESULTS
----------------
Classification: ${label}
AI Confidence: ${confidence}%
Model: YOLOv8 Neural Engine (TFLite Runtime)
Status: ${isNormal ? 'Normal — No significant anomalies detected' : 'Abnormal — Clinical review recommended'}

CLINICAL NOTES
--------------
This report was generated by TravelPal AI.
Results are for clinical reference only and should be
reviewed by a qualified medical professional.
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `TravelPal_Report_${patientId}_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="report-page" id="diagnostic-report-view">
      {/* Report Header */}
      <div className="report-header">
        <div className="report-logo-row">
          <span className="report-logo-icon">🔬</span>
          <span className="report-brand">TravelPal</span>
          <span className="report-badge">AI Diagnostic Report</span>
        </div>
        <h1 className="report-main-heading" id="report-heading">
          Diagnostic Report
        </h1>
        <p className="report-date">Generated: {formattedDate}</p>
      </div>

      <div className="report-body">
        {/* Patient Information Section */}
        <section className="report-section" id="patient-information-section">
          <h2 className="report-section-heading">
            👤 Patient Information
          </h2>
          <div className="report-info-grid">
            <div className="report-info-row">
              <span className="report-info-label">Patient ID</span>
              <span className="report-info-value" id="report-patient-id">
                {patientId}
              </span>
            </div>
            <div className="report-info-row">
              <span className="report-info-label">Patient Name</span>
              <span className="report-info-value" id="report-patient-name">
                {patientName}
              </span>
            </div>
            <div className="report-info-row">
              <span className="report-info-label">Scan Date</span>
              <span className="report-info-value">{formattedDate}</span>
            </div>
            <div className="report-info-row">
              <span className="report-info-label">Report ID</span>
              <span className="report-info-value">RPT-{Date.now().toString().slice(-8)}</span>
            </div>
          </div>
        </section>

        {/* Analysis Results Section */}
        <section className="report-section" id="analysis-results-section">
          <h2 className="report-section-heading">
            🔬 Analysis Results
          </h2>
          <div className={`report-result-banner ${isNormal ? 'banner-normal' : 'banner-abnormal'}`}>
            <div className="result-banner-icon">{isNormal ? '✅' : '⚠️'}</div>
            <div className="result-banner-content">
              <div className="result-banner-label">{label}</div>
              <div className="result-banner-sub">
                {isNormal
                  ? 'No significant pancreatic anomalies detected'
                  : 'Anomaly detected — clinical review strongly recommended'}
              </div>
            </div>
          </div>

          <div className="report-metrics-grid">
            <div className="report-metric-card">
              <div className="metric-card-label">AI Confidence Score</div>
              <div className="metric-card-value">{confidence}%</div>
              <div className="metric-bar-track">
                <div
                  className="metric-bar-fill"
                  style={{
                    width: `${confidence}%`,
                    background: isNormal
                      ? 'linear-gradient(90deg, #10b981, #34d399)'
                      : 'linear-gradient(90deg, #ef4444, #f97316)'
                  }}
                />
              </div>
            </div>
            <div className="report-metric-card">
              <div className="metric-card-label">Detection Model</div>
              <div className="metric-card-value" style={{ fontSize: '1rem', letterSpacing: 0 }}>YOLOv8</div>
              <div className="metric-card-sub">TFLite Runtime · On-Device</div>
            </div>
            <div className="report-metric-card">
              <div className="metric-card-label">Classification</div>
              <div className={`metric-card-value ${isNormal ? 'text-normal' : 'text-abnormal'}`}
                style={{ fontSize: '1rem' }}>
                {isNormal ? 'Normal' : 'Abnormal'}
              </div>
              <div className="metric-card-sub">Pancreatic CT Analysis</div>
            </div>
          </div>
        </section>

        {/* Clinical Disclaimer */}
        <section className="report-section report-disclaimer">
          <p>
            ⚕️ <strong>Clinical Disclaimer:</strong> This AI-generated report is intended to assist
            qualified medical professionals and does not constitute a definitive diagnosis.
            Results must be reviewed by a licensed radiologist or oncologist.
          </p>
        </section>
      </div>

      {/* Report Actions */}
      <div className="report-actions" id="report-action-buttons">
        <button
          className="report-btn report-btn-download"
          onClick={handleDownloadPDF}
          id="download-report-btn"
        >
          📥 Download PDF Report
        </button>
        <button
          className="report-btn report-btn-return"
          onClick={onReturnToDashboard}
          id="return-to-dashboard-btn"
        >
          ← Return to Dashboard
        </button>
      </div>
    </div>
  );
}
